name: xando
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  google_sign_in: ^6.1.6
  pay_with_paystack: ^1.0.6
  webview_flutter: ^4.4.2
  plugin_platform_interface: ^2.1.4
  flutterflow_ui: ^0.2.0+1
  firebase_auth: ^4.15.0
  connectivity_plus: ^5.0.2
  animated_custom_dropdown: ^2.0.0
  another_flushbar: ^1.12.30
  simple_gradient_text: 1.2.3
  loop_page_view: ^1.2.5
  flutter_keyboard_visibility: ^5.4.1
  pin_code_fields: 7.4.0
  easy_debounce: 2.0.1
  cupertino_icons: ^1.0.2
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.0
  from_css_color: 2.0.0
  google_fonts: 4.0.3
  intl: 0.18.1
  json_path: 0.6.2
  page_transition: 2.0.4
  path_provider: 2.0.14
  http: 
  provider: 6.0.4
  shared_preferences: 2.0.15
  smooth_page_indicator: 1.0.1
  firebase_core: ^2.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/


  fonts:
    - family: Bold
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf

    - family: Medium
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf

    - family: Regular
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf

    - family: Light
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
  
