name: xando
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+2

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  google_sign_in: ^6.1.6
  just_audio: ^0.9.36
  badges: ^3.1.2
  rive: 
  pay_with_paystack:
  email_otp:
  firebase_messaging: ^14.7.9
  onesignal_flutter: ^5.0.4
  share_plus: ^7.2.1
  url_launcher: ^6.2.2
  cloud_firestore: ^4.13.6
  webview_flutter: ^4.4.2
  flutterflow_ui: 
  firebase_auth: ^4.15.0
  connectivity_plus: ^5.0.2
  animated_custom_dropdown: ^2.0.0
  another_flushbar: ^1.12.30
  simple_gradient_text: 1.2.3
  loop_page_view: ^1.2.5
  pin_code_fields: 7.4.0
  easy_debounce: 2.0.1
  cupertino_icons: ^1.0.2
  flutter_animate: 
  google_fonts: 4.0.3
  intl: 
  page_transition: 2.0.4
  path_provider: 2.0.14
  http: 
  provider: 6.0.4
  shared_preferences: ^2.2.2
  smooth_page_indicator: 1.0.1
  firebase_core: ^2.24.0
  firebase_dynamic_links: ^5.4.8
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/x_indicator.png
    - assets/



  fonts:
    - family: Bold
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf

    - family: Medium
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf

    - family: Regular
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf

    - family: Light
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
  
